version: '3'

services:
  srv:
    build:
      context: .
      dockerfile: srv/Dockerfile
    volumes:
    - ./srv:/srv
    ports:
    - 5000:5000
    networks:
      - network
    depends_on:
      - db

  db:
   image: postgres:16
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   ports:
     - 5432:5432
   volumes:
     - db_data:/var/lib/postgresql/data
   networks:
     - network

  pga:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - pga_data:/var/lib/pgadmin
    networks:
     - network

volumes:
  db_data:
  pga_data:

networks:
  network:
    driver: bridge
